### PR TITLE
ci: publish edge image on push or pr to default_branch_ref

### PR DESCRIPTION
**Pull request by iwpnd**
Whenever something is pushed to Tegola default branch, publish an 0day/edge image.

### CODE REVIEW

**Comment by gdey** [comment]
This looks fine to me, but what is the reasoning behind it? Just so that we have a build that is on the latest version branch?

Nifty way of getting the current default branch!

**Comment by iwpnd** [comment]
That way I don’t have to fork the current default in my own image, when I for example want to use Redis SSL or the newest pgx. Edge always indicating that it is potentially not stable.

**Review by gdey — APPROVED** [review]
LGTM

**Comment by gdey** [comment]
FYI @ARolek is traveling right now, so I assume he will get to this sometime next week.

**Review by ARolek — APPROVED** [review]
LGTM! I like this addition. thank you!

**Pull request merged**
