### PR TITLE
cache/redis: add configurable key expiration time #600

### PR DESCRIPTION
**Pull request by tierpod**
PR for issue #600

### CODE REVIEW

**Comment by ARolek** [comment]
LGTM. Thank!

**Comment by ARolek** [comment]
@tierpod I have not merged this in yet because I'm debating internally if the config value should be `expires` or `ttl`. I'm starting to lean towards `ttl` for "Time To Live" as I think that better describes the value the user is setting. To me, `expires` seems like a specific time that the cache should expire the entry, rather than a time after setting the entry in the cache.

Thoughts?

**Comment by tierpod** [comment]
I agree with you. At the beginning I made "ttl" value but then I was a little confused with "Expiration" argument in redis.Set function. I have changed it today.

**Comment by ARolek** [comment]
@tierpod great! Thanks for the change.

**Pull request merged**
