### PR TITLE
Add 4326 tile rendering support

### PR DESCRIPTION
**Pull request by meilinger**
4326 OL5 test harness: [index.html.zip](https://github.com/go-spatial/tegola/files/3698886/index.html.zip)
Example config using OSM data: [tegola.toml.zip](https://github.com/go-spatial/tegola/files/3698895/tegola.toml.zip)

### CODE REVIEW

**Comment by ARolek** [comment]
Thank you! I might need to send in a PR to your PR to clean up the history a bit. In order to get v0.11.x released without geom I had to drop the geom commits. Let me think of a strategy and circle back.

**Comment by jorgejesus** [comment]
@meilinger 
Dear Joe, I tried to implement this PR: `http://dev-tiles.isric.org/capabilities/wosis.json` and run your OL5 code with my tile service, but it seems that is only 3857, I am not certain if I am doing a mistake on docker image. 

Is there a fast way to determine if `http://dev-tiles.isric.org` does actually support 4326, comparing with a production https://tiles.isric.org that is the latest docker image

**Comment by ARolek** [comment]
@jorgejesus we recently had to do a lot of juggling in this repo to unfreeze forward progress due to some additional work needing to be done to the underlying geom processing package. Due to this, this PR needs to be rebased / cleaned up and I don't know how stable it is at this time. @meilinger will have more insight on your specific question but I'm just giving you the heads up that projection support is still very much under development.

**Comment by meilinger** [comment]
Hi @jorgejesus! Sorry for the delay in getting back to you.  This PR needs to be built against https://github.com/ProminentEdge/geom/tree/add-tilegrid-4326 if I remember correctly in order to get the 4326 rendering support in place.  This probably could have been made much more clear in my original PR.  There isn't a quick way to know if the build includes 4326, unfortunately.  Let me know if you have any questions!

**Comment by ARolek** [comment]
Closing as we never got this to the finish line. Hopefully someday. @meilinger I hope you're doing well. Maybe we can revisit this in the not too distant future!

**Pull request closed without merging**
