### PR TITLE
fix: fix slice init length

### PR DESCRIPTION
**Pull request by cuishuang**
The intention here should be to initialize a slice with a capacity of `len(observers)` rather than initializing the length of this slice. 

The online demo: https://go.dev/play/p/q1BcVCmvidW

### CODE REVIEW

**Review by iwpnd — APPROVED** [review]
good catch

**Review by ARolek — APPROVED** [review]

**Review by gdey — APPROVED** [review]
LGTM! Good catch!

**Comment by ARolek** [comment]
@cuishuang please rebase this branch against master

**Comment by cuishuang** [comment]
> @cuishuang please rebase this branch against master

Updated. Please review again.

**Comment by ARolek** [comment]
This has been merged into master: https://github.com/go-spatial/tegola/commit/0f3131fbe428368012757aecfe38f57ec1844c6a

Thanks for the contribution!

**Pull request closed without merging**
