### PR TITLE
ci: rotate connection string

### PR DESCRIPTION
**Pull request by iwpnd**

### CODE REVIEW

**Comment by gdey** [comment]
@iwpnd did you see this comment?
https://github.com/go-spatial/tegola/pull/893#discussion_r1136602372

I don't think, did you add the secret to this repo already?

**Comment by iwpnd** [comment]
@ARolek just did 🙂

**Comment by ARolek** [comment]
Maybe this PR should just add comments above that connection string and reference the original post?

**Comment by iwpnd** [comment]
your pick

**Comment by ARolek** [comment]
Let's go with code commenting per the submitters request.

**Pull request closed without merging**
