### PR TITLE
Issue 189 Tile BBox coordinate order

### PR DESCRIPTION
**Pull request by JivanAmara**
Adds tests for a number of conversion functions, verifying WebMercator values.
Swaps the position of Tile.BoundingBox() y-values so the smaller of the two is placed in Miny.

### CODE REVIEW

**Comment by ARolek** [comment]
The v0.6.0 branch no longer exists. moving this to be based of the new v0.7.0 branch.

**Comment by JivanAmara** [comment]
Hey @ARolek, I vaguely remember you attending to this issue in v0.6.0.  Did that get completed, or do we still need to standardize bounding box coordinate order?

**Comment by gdey** [comment]
I'm pretty sure that got resolved. I'm working on consolidating our various bbox and extent types. There was a bit of intermingling of two ideas bbox which made up of (min, max) points and what I need for some of my algos, (upper-left,lower-right), which needs to know about the coordinate system it's in and does not always translate to (min, max). So, that is being sorted. I think this issue can be closed.

**Comment by ARolek** [comment]
@JivanAmara it's not fully resolved but did make some progress in v0.6.0. @gdey is working on plumbing this through but we're going to move to Bounds being `[4]float64{minx, miny, maxx, maxy}`

**Comment by ARolek** [comment]
I think this PR should be closed and delete after PR #357 has been accepted.

**Pull request closed without merging**
