### PR TITLE
Gpkg autoconfig

### PR DESCRIPTION
**Pull request by JivanAmara**
Adds an AutoConfig() function to gpkg provider.  The config includes all available feature tables.  This function provides what NewTileProvider() expects, not a config.toml.

Also extracted out metadata collection from NewTileProvider() into featureTableMetaData() so it can be reused in AutoConfig() & more rigorously tested.

### CODE REVIEW

**Comment by JivanAmara** [comment]
No changes, just rebased onto current v0.6.0.

**Comment by ARolek** [comment]
The v0.6.0 branch no longer exists. moving this to be based of the new v0.7.0 branch.

**Comment by JivanAmara** [comment]
Rebased onto v0.7.0

**Comment by ARolek** [comment]
I'm fine with this PR for it's near term purpose. AutoConfig is a great feature that I would like to eventually establish an interface around, but that should be handled in another issue.

**Pull request merged**
