### PR TITLE
Add configurable param example to README

### PR DESCRIPTION
**Pull request by bemyak**

### CODE REVIEW

**Review by ARolek — APPROVED** [review]
LGTM. Thank you!

**Review by gdey — APPROVED** [review]
LGMT

**Comment by trideset3** [comment]
Maybe also add `!PARAM!` to README in `providers.layers`? 

`sql = "SELECT ST_AsMVTGeom(geom,!BBOX!) AS geom, gid FROM gis.landuse WHERE geom && !BBOX! !PARAM!"`

**Comment by trideset3** [comment]
Maybe also add `!PARAM!` to README in `providers.layers` so it is more clear?

`sql = "SELECT ST_AsMVTGeom(geom,!BBOX!) AS geom, gid FROM gis.landuse WHERE geom && !BBOX! !PARAM!"`

**Comment by ARolek** [comment]
@trideset3 yeah that would help. Do you want to send in a quick PR with the documentation update?

**Comment by trideset3** [comment]
@ARolek sure, I'll open up a PR

**Pull request merged**
